version: "3.9"

services:
  app:
    build: .
    ports: 
      - "8000:8000"
    networks:
      - foodapp_network
    environment:
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_PASS=$DATABASE_PASS
      - DATABASE_NAME=$DATABASE_NAME
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - .:/home

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=foodapp_dbadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foodapp
    networks:
      - foodapp_network
    depends_on:
      - "app"

networks:
  foodapp_network: