"""Add user model

Revision ID: 58526d4e4b86
Revises: ebd877c2ecbc
Create Date: 2022-12-19 03:20:25.656735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58526d4e4b86"
down_revision = "ebd877c2ecbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=225), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=225), nullable=False),
        sa.Column("last_name", sa.String(length=225), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
