"""Replace Text with LargeBinary BYTEA

Revision ID: c0a40aa279be
Revises: 8b8fa77b3b96
Create Date: 2022-12-19 12:56:47.268515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0a40aa279be"
down_revision = "8b8fa77b3b96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.TEXT(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="hashed_password::bytea"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.LargeBinary(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
