name: packaging-code
on: push
jobs:
  codebase-linting:
    runs-on: ubuntu-latest
    container: python:3.8-alpine

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.8"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with black
        run: |
          black .
        
      - name: Test with pytest
        env:
          DATABASE_NAME: "postgres"
          DATABASE_PASS: "postgres"
          DATABASE_HOST: "localhost"
          DATABASE_USER: "postgres"
          DATABASE_PORT:  5432
        run: |
          pytest
  